/**
 * Terrain demo: one board, generated by the engine's seeded RNG.
 *
 * This is scaffolding for the eye, not the game (M1 Phase 3 replaces the
 * generation below with real tile-laying). What it already demonstrates:
 *
 *  - the presentation stack: spleen 5x8, 5x3-glyph cells, 5x5-cell tiles
 *  - determinism: the seed in the HUD fully decides the board; ?seed=N pins it
 *  - the layer boundaries: app wires engine (RNG) + content (palette) + render
 *  - the content pipeline: colours come from content/assets/palette.json,
 *    validated at load
 *
 * The per-glyph texture uses a stateless mixing hash, NOT the RNG - that is
 * the ASSETS.md rule: sequence randomness for choices, spatial hash for
 * texture, so redrawing never consumes randomness.
 */
import { GLTerm } from '@ascii-defense/render';
import type { GlyphSet } from '@ascii-defense/render';
import { createRng } from '@ascii-defense/engine';
import { validatePalette } from '@ascii-defense/content';
import paletteJson from '@ascii-defense/content/assets/palette.json';

const BASE = import.meta.env.BASE_URL;
const ASSET_V = '5';
const load = <T>(p: string): Promise<T> =>
  fetch(`${BASE}assets/${p}?v=${ASSET_V}`).then((r) => r.json() as Promise<T>);

interface TileDef { id: string; name: string; conn: string[]; cells: string[] }
interface TileDefs { tiles: TileDef[] }

// ---- palette: the one source of colour, validated through the pipeline -----

const paletteResult = validatePalette.check(paletteJson);
if (!paletteResult.ok) {
  throw new Error(
    'palette.json failed validation: ' +
      paletteResult.errors.map((e) => `${e.path}: ${e.message}`).join('; '),
  );
}
const ROLES = paletteResult.value.roles;
const role = (name: string): string => {
  const c = ROLES[name];
  if (!c) throw new Error(`palette role missing: ${name}`);
  return c;
};

const PATHS = [role('path.1'), role('path.2'), role('path.3'), role('path.4')];
const COLS: Record<string, [string, string, string]> = {
  G: [role('terrain.ground.mid'), role('terrain.ground.lit'), role('terrain.ground.dark')],
  R: [role('terrain.road.mid'), role('terrain.road.lit'), role('terrain.road.dark')],
  K: [role('terrain.rock.mid'), role('terrain.rock.lit'), role('terrain.rock.dark')],
  O: [role('terrain.ore.mid'), role('terrain.ore.lit'), role('terrain.ore.dark')],
  S: [role('terrain.spawn.mid'), role('terrain.spawn.lit'), role('terrain.spawn.dark')],
};

// ---- spleen styling (ASCII + braille + light box drawing only) -------------

const POOLS: Record<string, string> = {
  G: "          .'`,\u2800\u2801\u2802\u2804\u2808\u2810\u2820\u2840\u2880\u2803\u2809",
  R: ':;.,=\u2809\u2812\u2824\u2836\u281b\u283f-_~\u2810\u2820',
  K: '#%@&\u28ff\u287f\u28bf\u28fb\u28fd\u28fe\u28f7$WMB\u28f6\u28ef',
  O: '*+.o\u283f\u283e\u283d\u283bO0\u2837',
  S: '>>:.\u2808\u2818\u2838',
};
const TOWERS = [
  ['.-^-.', '|[O]|', "'---'"],
  ['\\ | /', '|(@)|', "'---'"],
  ['* . *', '|<8>|', "* ' *"],
  ['=====', '|{$}|', "'---'"],
];
const ENEMY = '<(o)>';
const CORE = /[O@$8]/;

// ---- grid geometry ---------------------------------------------------------

const TC = 5;                       // cells per tile side
const CW = 5, CH = 3;               // glyphs per cell
const TGX = TC * CW, TGY = TC * CH; // glyphs per tile side
const DIRS = { n: [0, -1], s: [0, 1], e: [1, 0], w: [-1, 0] } as const;
const OPP: Record<string, string> = { n: 's', s: 'n', e: 'w', w: 'e' };

/** Stateless mixing hash for per-glyph texture (ASSETS.md sec 5). */
function hash2(x: number, y: number, s: number): number {
  let h = (x | 0) * 374761393 + (y | 0) * 668265263 + s * 2246822519;
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}

/** The tile library is authored at 7x7; the demo board runs 5x5 cells. */
function to5(cells: string[]): string[] {
  const out: string[] = [];
  for (let y = 0; y < TC; y++) {
    let row = '';
    for (let x = 0; x < TC; x++) row += cells[Math.round((y * 6) / 4)][Math.round((x * 6) / 4)];
    out.push(row);
  }
  return out;
}

// ---- board generation: every choice draws from a named RNG stream ----------

function generateBoard(seed: number, lib: TileDef[], mapX: number, mapY: number): (TileDef | null)[] {
  const rng = createRng(seed);
  const map = rng.stream('map');
  const board: (TileDef | null)[] = new Array(mapX * mapY).fill(null);
  const get = (x: number, y: number): TileDef | null =>
    x < 0 || y < 0 || x >= mapX || y >= mapY ? null : board[y * mapX + x];

  const spawn = lib.find((t) => t.id === 'spawn_e')!;
  board[map.int(0, mapY - 1) * mapX] = spawn;

  for (let y = 0; y < mapY; y++)
    for (let x = 0; x < mapX; x++) {
      if (get(x, y)) continue;
      const cands = lib.filter((t) => {
        if (t.id === 'spawn_e') return false;
        for (const [dir, d] of Object.entries(DIRS)) {
          const nb = get(x + d[0], y + d[1]);
          if (!nb) continue;
          if (nb.conn.includes(OPP[dir]) !== t.conn.includes(dir)) return false;
        }
        return true;
      });
      if (!cands.length) continue;
      board[y * mapX + x] = map.pick(cands);
    }
  return board;
}

// ---- rendering -------------------------------------------------------------

function drawBoard(
  term: GLTerm,
  seed: number,
  lib: TileDef[],
  mapX: number,
  mapY: number,
  offsetY: number,
): void {
  const rng = createRng(seed);
  const decor = rng.stream('combat'); // decorative towers/enemies, own stream
  const board = generateBoard(seed, lib, mapX, mapY);

  term.clear(role('ui.bg'));
  term.write(0, 0, `ASCII DEFENSE \u00b7 terrain demo \u00b7 seed ${seed}`, role('ui.accent'));
  term.write(
    0,
    1,
    `click or press R to reroll \u00b7 ?seed=${seed} pins this exact board \u00b7 ${mapX}x${mapY} tiles \u00b7 tile 125x120px`,
    role('ui.dim'),
  );

  let towerN = 0;
  for (let ty = 0; ty < mapY; ty++)
    for (let tx = 0; tx < mapX; tx++) {
      const tile = board[ty * mapX + tx];
      if (!tile) continue;
      const cells = to5(tile.cells);
      for (let cy = 0; cy < TC; cy++)
        for (let cx = 0; cx < TC; cx++) {
          const kind = cells[cy][cx];
          const pool = POOLS[kind] ?? POOLS.G;
          const c3 = COLS[kind] ?? COLS.G;
          const gx0 = tx * TGX + cx * CW;
          const gy0 = offsetY + ty * TGY + cy * CH;
          // Texture: spatial hash, never the RNG - see file header.
          for (let y = 0; y < CH; y++)
            for (let x = 0; x < CW; x++) {
              const g = pool[Math.floor(hash2(gx0 + x, gy0 + y, 6) * pool.length) % pool.length];
              term.put(gx0 + x, gy0 + y, g, hash2(gx0 + x, gy0 + y, 9) < 0.2 ? c3[1] : c3[0], c3[2]);
            }
          // Decoration: sequence RNG, so density stays honest per seed.
          if (kind === 'G' && decor.chance(0.22)) {
            const art = TOWERS[towerN % TOWERS.length];
            const col = PATHS[towerN % PATHS.length];
            towerN++;
            for (let r = 0; r < Math.min(CH, art.length); r++)
              for (let c = 0; c < Math.min(CW, art[r].length); c++) {
                const chr = art[r][c];
                if (chr === ' ' || !term.has(chr)) continue;
                term.put(gx0 + c, gy0 + r, chr, CORE.test(chr) ? col : role('tower.frame'), role('tower.ground'));
              }
          }
          if (kind === 'R' && decor.chance(0.15))
            for (let i = 0; i < Math.min(CW, ENEMY.length); i++)
              if (term.has(ENEMY[i])) term.put(gx0 + i, gy0, ENEMY[i], role('enemy.eye'), COLS.R[2]);
        }
    }
  term.flush();
}

// ---- bootstrap -------------------------------------------------------------

async function main(): Promise<void> {
  const [glyphs, defs] = await Promise.all([
    load<GlyphSet>('glyphset-spleen.json'),
    load<TileDefs>('tiledefs.json'),
  ]);

  const app = document.getElementById('app')!;
  const mapX = 14, mapY = 7;
  const OY = 3; // HUD rows above the board
  const term = new GLTerm(glyphs, {
    cols: mapX * TGX,
    rows: mapY * TGY + OY,
    cellPx: 5,
    cellPxH: 8,
    background: role('ui.bg'),
  });

  // Seed from the URL if pinned, else from the clock (Math.random is banned
  // everywhere, and the whole point is that the seed is the only entropy).
  const fromUrl = Number(new URLSearchParams(location.search).get('seed'));
  let seed = Number.isInteger(fromUrl) && fromUrl > 0 ? fromUrl : Date.now() % 1_000_000;

  const draw = (): void => {
    drawBoard(term, seed, defs.tiles, mapX, mapY, OY);
    history.replaceState(null, '', `?seed=${seed}`);
  };

  const reroll = (): void => {
    seed = (seed + 1 + (Date.now() % 997)) % 1_000_000;
    draw();
  };

  app.appendChild(term.canvas);
  const cap = document.createElement('div');
  cap.className = 'hud';
  cap.textContent =
    `spleen 5x8 \u00b7 ${glyphs.codepoints.length} glyphs in font \u00b7 ` +
    `palette: content/assets/palette.json (validated at load) \u00b7 ` +
    `board + decoration from engine RNG streams 'map' + 'combat'`;
  app.appendChild(cap);

  term.canvas.addEventListener('click', reroll);
  window.addEventListener('keydown', (e) => {
    if (e.key === 'r' || e.key === 'R') reroll();
  });

  draw();
}

main().catch((e) => {
  document.getElementById('app')!.textContent = `failed: ${String(e)}`;
  console.error(e);
});
